--- #YAML:1.0
name:               XML-ApplyXSLT
version:            0.52
abstract:           convert XML data with XSLT stylesheet files
author:
    - Jeremy Mates <jmates@sial.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::LibXML:   1.53
    XML::LibXSLT:  1.5
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
