# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-ApplyXSLT
version:      0.50
version_from: lib/XML/ApplyXSLT.pm
installdirs:  site
requires:
    XML::LibXML:                   1.53
    XML::LibXSLT:                  1.5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
