#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-ApplyXSLT
version:      0.42
version_from: lib/XML/ApplyXSLT.pm
installdirs:  site
requires:
    XML::LibXSLT:                  1.52
    XML::LibXML:                   1.53

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
